### ISSUE TITLE
style sheet and javascript tags injected as raw text, not activated

### ISSUE THREAD

**Issue by mistergibson** [koa/refinerycms-multisite#5]
This is the output after generating with multisite: https://gist.github.com/1035968

Notice that instead of a purdy and spiffy themed page, I get the head tag css and js tags injected as content text and not activated head subtags.

Any idea how I can fix this?

Thanks

**Comment by JasonTrue** [comment]
I haven't been able to reproduce this behavior. It looks like a layouts/application file is not in the place that Rails expects to find it, and it doesn't sound particularly related to the multisite gem.

Did you add the multisite gem to a project where you had already run the refinery generator? That's how I did it.

I think it would be helpful to see your project somewhere, or a complete history of your command-line activities plus your Gemfile.

**Comment by mistergibson** [comment]
sorry for the delayed response -- let me do a bit more on this and get back to you.  I also spotted some other bugs in other engines on a mad fest of 'throw it all together and watch it blow up' approach to alpha site experimentation.  I'll narrow it down and post info.

**Comment by JasonTrue** [comment]
At this point, the only engine that Multisite modifies at this point is the Pages engine, so most of the other existing Refinery features aren't affected by it; you can take advantage of the site model for any Refinery engine that you build yourself.

Koa and I are probably the primary users of this at this point, and I only started working with it because it was nearly a spitting image of the hack that I first threw together to support a multisite application and I didn't feel it was a good idea to attack the problem completely on my own when someone else was trying to solve the same problem. Up to this point, everything that's in this project have been put there because either he or I needed it for our respective projects, so expect major gaps in functionality.

**Comment by koa** [comment]
Sorry my late reaction but i was in vacation and think i can nothing add to JasonTrue's statement.
If you have a fix/improvment for the multisite-plugin i will intergrate it (if it breaks nothing else)
